# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Qt\TST\BatchNueBee\NueBee.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 642)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_batches = QtWidgets.QWidget()
        self.tab_batches.setObjectName("tab_batches")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_batches)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_batches)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_tst2 = QtWidgets.QPushButton(self.tab_batches)
        self.pushButton_tst2.setObjectName("pushButton_tst2")
        self.gridLayout.addWidget(self.pushButton_tst2, 1, 0, 1, 1)
        self.pushButton_tst5 = QtWidgets.QPushButton(self.tab_batches)
        self.pushButton_tst5.setObjectName("pushButton_tst5")
        self.gridLayout.addWidget(self.pushButton_tst5, 4, 0, 1, 1)
        self.pushButton_tst4 = QtWidgets.QPushButton(self.tab_batches)
        self.pushButton_tst4.setObjectName("pushButton_tst4")
        self.gridLayout.addWidget(self.pushButton_tst4, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.pushButton_tst6 = QtWidgets.QPushButton(self.tab_batches)
        self.pushButton_tst6.setObjectName("pushButton_tst6")
        self.gridLayout.addWidget(self.pushButton_tst6, 5, 0, 1, 1)
        self.pushButton_tst1 = QtWidgets.QPushButton(self.tab_batches)
        self.pushButton_tst1.setObjectName("pushButton_tst1")
        self.gridLayout.addWidget(self.pushButton_tst1, 0, 0, 1, 1)
        self.pushButton_tst3 = QtWidgets.QPushButton(self.tab_batches)
        self.pushButton_tst3.setObjectName("pushButton_tst3")
        self.gridLayout.addWidget(self.pushButton_tst3, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.setStretch(0, 9)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_2.setStretch(0, 9)
        self.verticalLayout_2.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_batches, "")
        self.tab_trends = QtWidgets.QWidget()
        self.tab_trends.setObjectName("tab_trends")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_trends)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_trends)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setVerticalSpacing(7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.toolButton_add_group = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_add_group.setMinimumSize(QtCore.QSize(28, 28))
        self.toolButton_add_group.setObjectName("toolButton_add_group")
        self.gridLayout_3.addWidget(self.toolButton_add_group, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 1, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_trends)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_app_vessels = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_app_vessels.setObjectName("listWidget_app_vessels")
        self.gridLayout_4.addWidget(self.listWidget_app_vessels, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_trends)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_Trends = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_Trends.setObjectName("tableWidget_Trends")
        self.tableWidget_Trends.setColumnCount(0)
        self.tableWidget_Trends.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget_Trends, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_3.setStretch(0, 4)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_trends)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout_5.addWidget(self.toolButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.toolButton = QtWidgets.QToolButton(self.tab_trends)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_5.addWidget(self.toolButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_5.setStretch(0, 6)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(4, 6)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_pens = QtWidgets.QTableWidget(self.tab_trends)
        self.tableWidget_pens.setObjectName("tableWidget_pens")
        self.tableWidget_pens.setColumnCount(0)
        self.tableWidget_pens.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_pens)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(2, 10)
        self.tabWidget.addTab(self.tab_trends, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NueBee"))
        self.tableWidget.setSortingEnabled(False)
        self.pushButton_tst2.setText(_translate("MainWindow", "Test2"))
        self.pushButton_tst5.setText(_translate("MainWindow", "Test5"))
        self.pushButton_tst4.setText(_translate("MainWindow", "Test4"))
        self.pushButton_tst6.setText(_translate("MainWindow", "Test6"))
        self.pushButton_tst1.setText(_translate("MainWindow", "Test1"))
        self.pushButton_tst3.setText(_translate("MainWindow", "Test3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_batches), _translate("MainWindow", "Batches"))
        self.groupBox.setTitle(_translate("MainWindow", "Trends Group"))
        self.pushButton.setText(_translate("MainWindow", "CANCEL"))
        self.toolButton_add_group.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "SAVE"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Applicable Vessel Types"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Trends"))
        self.toolButton_2.setText(_translate("MainWindow", "<"))
        self.toolButton.setText(_translate("MainWindow", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trends), _translate("MainWindow", "Trends"))

